name: Deploy

on:
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Surge
        run: npm install -g surge

      - name: Install packages
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Deploy to surge
        run: surge ./dist zonked-grip.surge.sh --token ${{ secrets.SURGE_ACCESS_TOKEN }}


