name: Deploy

on:
  push:
    branches: main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Surge
        run: npm install -g surge

      - name: Install packages
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Deploy to surge
        run: surge ./dist zonked-grip.surge.sh --token ${{ secrets.SURGE_ACCESS_TOKEN }}

      - name: Update repo website
        run: |
          curl -X PATCH \
               -H "Authorization: token ${{ secrets.GH_REPO_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }} \
               -d '{"homepage": "http://zonked-grip.surge.sh"}'
